name: Flutter Build & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --build-name=1.0.${{ github.run_number }} --build-number=${{ github.run_number }} -v > build_log.txt 2>&1 || true

      - name: Commit Log
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add build_log.txt
          git commit -m "Upload build log"
          git push

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v1.0.${{ github.run_number }}"
          name: "Release v1.0.${{ github.run_number }}"
          body: "Auto-generated release from latest push to main."
